export const champions = {
    top: [
      { name: "Aatrox", image: "Aatrox" },
      { name: "Akali", image: "Akali" },
      { name: "Camille", image: "Camille" },
      { name: "Cho’Gath", image: "Chogath" },
      { name: "Darius", image: "Darius" },
      { name: "Dr. Mundo", image: "DrMundo" },
      { name: "Fiora", image: "Fiora" },
      { name: "Gangplank", image: "Gangplank" },
      { name: "Garen", image: "Garen" },
      { name: "Gnar", image: "Gnar" },
      { name: "Gragas", image: "Gragas" },
      { name: "Gwen", image: "Gwen" },
      { name: "Illaoi", image: "Illaoi" },
      { name: "Irelia", image: "Irelia" },
      { name: "Jax", image: "Jax" },
      { name: "Jayce", image: "Jayce" },
      { name: "Kayle", image: "Kayle" },
      { name: "Kennen", image: "Kennen" },
      { name: "Kled", image: "Kled" },
      { name: "Lillia", image: "Lillia" },
      { name: "Malphite", image: "Malphite" },
      { name: "Mordekaiser", image: "Mordekaiser" },
      { name: "Nasus", image: "Nasus" },
      { name: "Olaf", image: "Olaf" },
      { name: "Ornn", image: "Ornn" },
      { name: "Quinn", image: "Quinn" },
      { name: "Renekton", image: "Renekton" },
      { name: "Riven", image: "Riven" },
      { name: "Rumble", image: "Rumble" },
      { name: "Sejuani", image: "Sejuani" },
      { name: "Sett", image: "Sett" },
      { name: "Shen", image: "Shen" },
      { name: "Shyvana", image: "Shyvana" },
      { name: "Singed", image: "Singed" },
      { name: "Sion", image: "Sion" },
      { name: "Sion", image: "Sion" },
      { name: "Tahm Kench", image: "TahmKench" },
      { name: "Teemo", image: "Teemo" },
      { name: "Tryndamere", image: "Tryndamere" },
      { name: "Urgot", image: "Urgot" },
      { name: "Vayne", image: "Vayne" },
      { name: "Volibear", image: "Volibear" },
      { name: "Wukong", image: "MonkeyKing" },
      { name: "Yasuo", image: "Yasuo" },
      { name: "Yone", image: "Yone" },
      { name: "Yorick", image: "Yorick" }
    ],
    jungle: [
        { name: "Amumu", image: "Amumu" },
        { name: "Bel’Veth", image: "BelVeth" },
        { name: "Diana", image: "Diana" },
        { name: "Ekko", image: "Ekko" },
        { name: "Elise", image: "Elise" },
        { name: "Evelynn", image: "Evelynn" },
        { name: "Fiddlesticks", image: "Fiddlesticks" },
        { name: "Graves", image: "Graves" },
        { name: "Hecarim", image: "Hecarim" },
        { name: "Ivern", image: "Ivern" },
        { name: "Jarvan IV", image: "JarvanIV" },
        { name: "Karthus", image: "Karthus" },
        { name: "Kayn", image: "Kayn" },
        { name: "Kha’Zix", image: "Khazix" },
        { name: "Kindred", image: "Kindred" },
        { name: "Lee Sin", image: "LeeSin" },
        { name: "Lillia", image: "Lillia" },
        { name: "Master Yi", image: "MasterYi" },
        { name: "Nidalee", image: "Nidalee" },
        { name: "Nocturne", image: "Nocturne" },
        { name: "Nunu & Willump", image: "NunuWillump" },
        { name: "Pantheon", image: "Pantheon" },
        { name: "Poppy", image: "Poppy" },
        { name: "Rammus", image: "Rammus" },
        { name: "Rek’Sai", image: "RekSai" },
        { name: "Rengar", image: "Rengar" },
        { name: "Sejuani", image: "Sejuani" },
        { name: "Shaco", image: "Shaco" },
        { name: "Shyvana", image: "Shyvana" },
        { name: "Skarner", image: "Skarner" },
        { name: "Taliyah", image: "Taliyah" },
        { name: "Talon", image: "Talon" },
        { name: "Trundle", image: "Trundle" },
        { name: "Udyr", image: "Udyr" },
        { name: "Vi", image: "Vi" },
        { name: "Viego", image: "Viego" },
        { name: "Volibear", image: "Volibear" },
        { name: "Warwick", image: "Warwick" },
        { name: "Wukong", image: "MonkeyKing" },
        { name: "Xin Zhao", image: "XinZhao" },
        { name: "Zac", image: "Zac" },
        { name: "Zed", image: "Zed" }
      ],
      mid: [
        { name: "Ahri", image: "Ahri" },
        { name: "Akali", image: "Akali" },
        { name: "Akshan", image: "Akshan" },
        { name: "Anivia", image: "Anivia" },
        { name: "Annie", image: "Annie" },
        { name: "Aurelion Sol", image: "AurelionSol" },
        { name: "Azir", image: "Azir" },
        { name: "Cassiopeia", image: "Cassiopeia" },
        { name: "Corki", image: "Corki" },
        { name: "Ekko", image: "Ekko" },
        { name: "Fizz", image: "Fizz" },
        { name: "Galio", image: "Galio" },
        { name: "Gangplank", image: "Gangplank" },
        { name: "Heimerdinger", image: "Heimerdinger" },
        { name: "Irelia", image: "Irelia" },
        { name: "Kassadin", image: "Kassadin" },
        { name: "Katarina", image: "Katarina" },
        { name: "LeBlanc", image: "LeBlanc" },
        { name: "Lissandra", image: "Lissandra" },
        { name: "Lux", image: "Lux" },
        { name: "Malzahar", image: "Malzahar" },
        { name: "Neeko", image: "Neeko" },
        { name: "Orianna", image: "Orianna" },
        { name: "Qiyana", image: "Qiyana" },
        { name: "Ryze", image: "Ryze" },
        { name: "Swain", image: "Swain" },
        { name: "Sylas", image: "Sylas" },
        { name: "Syndra", image: "Syndra" },
        { name: "Taliyah", image: "Taliyah" },
        { name: "Talon", image: "Talon" },
        { name: "Twisted Fate", image: "TwistedFate" },
        { name: "Veigar", image: "Veigar" },
        { name: "Vex", image: "Vex" },
        { name: "Viktor", image: "Viktor" },
        { name: "Vladimir", image: "Vladimir" },
        { name: "Xerath", image: "Xerath" },
        { name: "Yasuo", image: "Yasuo" },
        { name: "Yone", image: "Yone" },
        { name: "Zed", image: "Zed" },
        { name: "Ziggs", image: "Ziggs" },
        { name: "Zoe", image: "Zoe" }
      ],
      bot: [
        { name: "Aphelios", image: "Aphelios" },
        { name: "Ashe", image: "Ashe" },
        { name: "Caitlyn", image: "Caitlyn" },
        { name: "Draven", image: "Draven" },
        { name: "Ezreal", image: "Ezreal" },
        { name: "Jhin", image: "Jhin" },
        { name: "Jinx", image: "Jinx" },
        { name: "Kai’Sa", image: "Kaisa" },
        { name: "Kalista", image: "Kalista" },
        { name: "Kog’Maw", image: "KogMaw" },
        { name: "Lucian", image: "Lucian" },
        { name: "Miss Fortune", image: "MissFortune" },
        { name: "Nilah", image: "Nilah" },
        { name: "Samira", image: "Samira" },
        { name: "Sivir", image: "Sivir" },
        { name: "Tristana", image: "Tristana" },
        { name: "Twitch", image: "Twitch" },
        { name: "Varus", image: "Varus" },
        { name: "Vayne", image: "Vayne" },
        { name: "Xayah", image: "Xayah" },
        { name: "Yasuo", image: "Yasuo" },
        { name: "Zeri", image: "Zeri" },
        { name: "Ziggs", image: "Ziggs" }
      ],
      support: [
        { name: "Alistar", image: "Alistar" },
        { name: "Amumu", image: "Amumu" },
        { name: "Ashe", image: "Ashe" },
        { name: "Bard", image: "Bard" },
        { name: "Blitzcrank", image: "Blitzcrank" },
        { name: "Brand", image: "Brand" },
        { name: "Braum", image: "Braum" },
        { name: "Janna", image: "Janna" },
        { name: "Karma", image: "Karma" },
        { name: "Leona", image: "Leona" },
        { name: "Lulu", image: "Lulu" },
        { name: "Lux", image: "Lux" },
        { name: "Maokai", image: "Maokai" },
        { name: "Miss Fortune", image: "MissFortune" },
        { name: "Morgana", image: "Morgana" },
        { name: "Nami", image: "Nami" },
        { name: "Nautilus", image: "Nautilus" },
        { name: "Pantheon", image: "Pantheon" },
        { name: "Pyke", image: "Pyke" },
        { name: "Rakan", image: "Rakan" },
        { name: "Rell", image: "Rell" },
        { name: "Renata Glasc", image: "RenataGlasc" },
        { name: "Senna", image: "Senna" },
        { name: "Seraphine", image: "Seraphine" },
        { name: "Sona", image: "Sona" },
        { name: "Soraka", image: "Soraka" },
        { name: "Swain", image: "Swain" },
        { name: "Taric", image: "Taric" },
        { name: "Thresh", image: "Thresh" },
        { name: "Vel’Koz", image: "VelKoz" },
        { name: "Xerath", image: "Xerath" },
        { name: "Yuumi", image: "Yuumi" },
        { name: "Zilean", image: "Zilean" },
        { name: "Zyra", image: "Zyra" }
      ]
  };